build:
  binary: picasso
  main: main.go
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ignore:
      - goos: darwin
        goarch: 386
  env:
    - CGO_ENABLED=0
  ldflags:
      - -s -w

gomod:
  proxy: true

release:
  draft: true

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "task_checksums.txt"
