version: 1

author: Sebastian Döll <sebastian@katallaxie.me>

project: Picasso

build:
  preRun:
    desc: before run
    vars:
      region:
        - test
    cmds:
      - go test -v ./...
    templates:
      - 
        file: ./examples/config.json.tpl
        output: ./config.json
        vars:
          foo: bar
      