version: 1

author: Sebastian Döll <sebastian@katallaxie.me>

project: Picasso

tasks:
  build:
    desc: before run
    vars:
      region:
        - test
    cmds:
      - go test -v ./...
    watch:
      paths:
        - examples
      ignore:
        - .gitignore
        - .picasso.yml
    templates:
      - 
        file: ./examples/config.json.tpl
        output: ./config.json
        vars:
          foo: bar
      