version: 1

author: Sebastian Döll <sebastian@katallaxie.me>

project: Picasso

tasks:
  watch:
    cmds:
      - go test -v -race ./...
    paths:
      - examples
    ignore:
      - .gitignore
      - .picasso.yml

  preRun:
    desc: before run
    vars:
      region:
        - test
    cmds:
      - go test -v ./...
    templates:
      - 
        file: ./examples/config.json.tpl
        output: ./config.json
        vars:
          foo: bar
      