language: go

matrix:
  include:
  - go: 1.11.x
  - go: 1.12.x
    env: LATEST=true
  - go: tip
  allow_failures:
  - go: tip

addons:
  apt:
    packages:
      - rpm

notifications:
  slack:
    rooms:
      secure: TLH9zXNPvHqn/gigELjAm0gor3d/umk+zGM+NTEoeybwge3P1LeyXbVJPxj1zOYQ9CogV022nfiACp5M1HLMjA9VSMEcFNE8Hy+yIkVM89K11WgcVPCsPapOZ3twMV6CcHn3TxFnvyackqsP2C6xLn3UyQ1fkiVm+vkJVGyoWj6kvwr06ZmCMtTlC5aYU8BB0135V7GuUywFrMCASGRhE11F5oZvRkhVi0M8LtgwDGyWJiFIhtQYCwdbSn/jS2OJoItgp7FhVZSEfoGOWrnHyJ6IESZOpfHMPUL8nv0B4q+PTSVrhsP1Lj0lvoyCB64lEkusakLqQERWMP+/NdIbLr4SaonpMHAYDSMHt8MX3mZu8NpqEaf7+sWX2tMcfOsn9iIw9ghfuuNqU3KAHZyt6bDb0deEiaAn3ZcPdMAMwkSbiRB1fUuWQOqOurYmvW8EGqxZDWAIb7hbGa+ga4Dq3ctlfRwedXjQu7w3epuni412w1gMlWLnRL4Cz6WwyxB2WnN13vbZrRi/UoztPDe7rvdipEUZNPu0EVopIDtXh1I3qJNPMEXcwos1zyIoG/vIDyKps1khaL9vznhPlSl0/2ByMgO91KxUpFt7UOKPBK4OvbkOXGTtrBFM7GvYiLSz7O4jHHqVyKnLyuMq5n69MPAsWzM24aL/e2YpfvcvDBE=

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
