package spec

// Spec ...
type Spec struct {
	// Spec ...
	Spec string `validate:"required"`
	// Version ...
	Version string `validate:"required"`
	// Description ...
	Description string
	// Author ...
	Author string `validate:"required"`
	// Includes ...
	Includes []string `validate:"required_with=Excludes"`
	// include ...
	Excludes []string
	// Template...
	Template Template
}

// Template ...
type Template struct {
	// Placeholders ...
	Placeholders []Placeholder
}

// Placeholder ...
type Placeholder struct {
	// Name ...
	Name string `validate:"required"`
	// Type ...
	Type string `validate:"required"`
	// Prompt ...
	Prompt string `validate:"required"`
	// Regex ...
	Regex string
}
