package specs

// Spec ...
type Spec struct {
	// Spec ...
	Spec string `validate:"required"`
	// Version ...
	Version string `validate:"required"`
	// Description ...
	Description string
	// Author ...
	Author string `validate:"required"`
	// Includes ...
	Includes []string `validate:"required_with=Excludes"`
	// include ...
	Excludes []string
}
