package specs

const (
	// TmplFile ...
	TmplFile = ".template.yml"
)

// Tmpl ...
type Tmpl struct {
	// Spec ...
	Spec string `validate:"required"`
	// Version ...
	Version string `validate:"required"`
	// Includes ...
	Includes []string `validate:"required_with=Excludes"`
	// Excludes ...
	Excludes []string
	// Ignores ...
	Ignores []string
	// Inputs...
	Inputs TmplInputs
}

// TmplInputs ...
type TmplInputs []TmplInput

// Input ...
type TmplInput struct {
	// Name ...
	Name string `validate:"required"`
	// Type ...
	Type string `validate:"required"`
	// Prompt ...
	Prompt string `validate:"required"`
	// Regex ...
	Regex string
}
