// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: pkg/proto/spec.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Spec ...
type Spec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spec        string            `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Name        string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version     string            `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description string            `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Authors     []string          `protobuf:"bytes,5,rep,name=authors,proto3" json:"authors,omitempty"`
	Homepage    string            `protobuf:"bytes,6,opt,name=homepage,proto3" json:"homepage,omitempty"`
	License     string            `protobuf:"bytes,7,opt,name=license,proto3" json:"license,omitempty"`
	Repository  string            `protobuf:"bytes,8,opt,name=repository,proto3" json:"repository,omitempty"`
	Plugins     []*Spec_Plugin    `protobuf:"bytes,9,rep,name=plugins,proto3" json:"plugins,omitempty"`
	Tasks       []*Spec_Task      `protobuf:"bytes,10,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Generators  []*Spec_Generator `protobuf:"bytes,11,rep,name=generators,proto3" json:"generators,omitempty"`
}

func (x *Spec) Reset() {
	*x = Spec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_spec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_spec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_pkg_proto_spec_proto_rawDescGZIP(), []int{0}
}

func (x *Spec) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *Spec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Spec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Spec) GetAuthors() []string {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *Spec) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *Spec) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *Spec) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *Spec) GetPlugins() []*Spec_Plugin {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *Spec) GetTasks() []*Spec_Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *Spec) GetGenerators() []*Spec_Generator {
	if x != nil {
		return x.Generators
	}
	return nil
}

// Template ...
type Spec_Template struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Includes []string               `protobuf:"bytes,1,rep,name=includes,proto3" json:"includes,omitempty"`
	Excludes []string               `protobuf:"bytes,2,rep,name=excludes,proto3" json:"excludes,omitempty"`
	Inputs   []*Spec_Template_Input `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
}

func (x *Spec_Template) Reset() {
	*x = Spec_Template{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_spec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spec_Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_Template) ProtoMessage() {}

func (x *Spec_Template) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_spec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_Template.ProtoReflect.Descriptor instead.
func (*Spec_Template) Descriptor() ([]byte, []int) {
	return file_pkg_proto_spec_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Spec_Template) GetIncludes() []string {
	if x != nil {
		return x.Includes
	}
	return nil
}

func (x *Spec_Template) GetExcludes() []string {
	if x != nil {
		return x.Excludes
	}
	return nil
}

func (x *Spec_Template) GetInputs() []*Spec_Template_Input {
	if x != nil {
		return x.Inputs
	}
	return nil
}

// Task ...
type Spec_Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Commands    []string              `protobuf:"bytes,4,rep,name=commands,proto3" json:"commands,omitempty"`
	Disabled    bool                  `protobuf:"varint,5,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Default     bool                  `protobuf:"varint,6,opt,name=default,proto3" json:"default,omitempty"`
	DependsOn   []string              `protobuf:"bytes,7,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	Vars        map[string]string     `protobuf:"bytes,8,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Watch       []*Spec_Task_Watch    `protobuf:"bytes,9,rep,name=watch,proto3" json:"watch,omitempty"`
	Templates   []*Spec_Task_Template `protobuf:"bytes,10,rep,name=templates,proto3" json:"templates,omitempty"`
}

func (x *Spec_Task) Reset() {
	*x = Spec_Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_spec_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spec_Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_Task) ProtoMessage() {}

func (x *Spec_Task) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_spec_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_Task.ProtoReflect.Descriptor instead.
func (*Spec_Task) Descriptor() ([]byte, []int) {
	return file_pkg_proto_spec_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Spec_Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Spec_Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spec_Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Spec_Task) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Spec_Task) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Spec_Task) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

func (x *Spec_Task) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *Spec_Task) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *Spec_Task) GetWatch() []*Spec_Task_Watch {
	if x != nil {
		return x.Watch
	}
	return nil
}

func (x *Spec_Task) GetTemplates() []*Spec_Task_Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

// Plugin ...
type Spec_Plugin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Path        string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *Spec_Plugin) Reset() {
	*x = Spec_Plugin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_spec_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spec_Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_Plugin) ProtoMessage() {}

func (x *Spec_Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_spec_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_Plugin.ProtoReflect.Descriptor instead.
func (*Spec_Plugin) Descriptor() ([]byte, []int) {
	return file_pkg_proto_spec_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Spec_Plugin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Spec_Plugin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spec_Plugin) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Spec_Plugin) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Generator ...
type Spec_Generator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path     string                  `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Includes []string                `protobuf:"bytes,4,rep,name=includes,proto3" json:"includes,omitempty"`
	Excludes []string                `protobuf:"bytes,5,rep,name=excludes,proto3" json:"excludes,omitempty"`
	Inputs   []*Spec_Generator_Input `protobuf:"bytes,6,rep,name=inputs,proto3" json:"inputs,omitempty"`
}

func (x *Spec_Generator) Reset() {
	*x = Spec_Generator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_spec_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spec_Generator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_Generator) ProtoMessage() {}

func (x *Spec_Generator) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_spec_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_Generator.ProtoReflect.Descriptor instead.
func (*Spec_Generator) Descriptor() ([]byte, []int) {
	return file_pkg_proto_spec_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Spec_Generator) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Spec_Generator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spec_Generator) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Spec_Generator) GetIncludes() []string {
	if x != nil {
		return x.Includes
	}
	return nil
}

func (x *Spec_Generator) GetExcludes() []string {
	if x != nil {
		return x.Excludes
	}
	return nil
}

func (x *Spec_Generator) GetInputs() []*Spec_Generator_Input {
	if x != nil {
		return x.Inputs
	}
	return nil
}

// Input ...
type Spec_Template_Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Prompt string `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Regex  string `protobuf:"bytes,4,opt,name=regex,proto3" json:"regex,omitempty"`
}

func (x *Spec_Template_Input) Reset() {
	*x = Spec_Template_Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_spec_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spec_Template_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_Template_Input) ProtoMessage() {}

func (x *Spec_Template_Input) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_spec_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_Template_Input.ProtoReflect.Descriptor instead.
func (*Spec_Template_Input) Descriptor() ([]byte, []int) {
	return file_pkg_proto_spec_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Spec_Template_Input) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spec_Template_Input) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Spec_Template_Input) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Spec_Template_Input) GetRegex() string {
	if x != nil {
		return x.Regex
	}
	return ""
}

// Watch ...
type Spec_Task_Watch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths   []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	Ignores []string `protobuf:"bytes,2,rep,name=ignores,proto3" json:"ignores,omitempty"`
}

func (x *Spec_Task_Watch) Reset() {
	*x = Spec_Task_Watch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_spec_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spec_Task_Watch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_Task_Watch) ProtoMessage() {}

func (x *Spec_Task_Watch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_spec_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_Task_Watch.ProtoReflect.Descriptor instead.
func (*Spec_Task_Watch) Descriptor() ([]byte, []int) {
	return file_pkg_proto_spec_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *Spec_Task_Watch) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *Spec_Task_Watch) GetIgnores() []string {
	if x != nil {
		return x.Ignores
	}
	return nil
}

// Template ...
type Spec_Task_Template struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string            `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	File        string            `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Out         string            `protobuf:"bytes,4,opt,name=out,proto3" json:"out,omitempty"`
	Vars        map[string]string `protobuf:"bytes,5,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Spec_Task_Template) Reset() {
	*x = Spec_Task_Template{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_spec_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spec_Task_Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_Task_Template) ProtoMessage() {}

func (x *Spec_Task_Template) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_spec_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_Task_Template.ProtoReflect.Descriptor instead.
func (*Spec_Task_Template) Descriptor() ([]byte, []int) {
	return file_pkg_proto_spec_proto_rawDescGZIP(), []int{0, 1, 2}
}

func (x *Spec_Task_Template) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spec_Task_Template) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Spec_Task_Template) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Spec_Task_Template) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

func (x *Spec_Task_Template) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

// Input ...
type Spec_Generator_Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Prompt string `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Regex  string `protobuf:"bytes,4,opt,name=regex,proto3" json:"regex,omitempty"`
}

func (x *Spec_Generator_Input) Reset() {
	*x = Spec_Generator_Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_spec_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spec_Generator_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec_Generator_Input) ProtoMessage() {}

func (x *Spec_Generator_Input) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_spec_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec_Generator_Input.ProtoReflect.Descriptor instead.
func (*Spec_Generator_Input) Descriptor() ([]byte, []int) {
	return file_pkg_proto_spec_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *Spec_Generator_Input) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spec_Generator_Input) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Spec_Generator_Input) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Spec_Generator_Input) GetRegex() string {
	if x != nil {
		return x.Regex
	}
	return ""
}

var File_pkg_proto_spec_proto protoreflect.FileDescriptor

var file_pkg_proto_spec_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x65, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd9, 0x0c,
	0x0a, 0x04, 0x53, 0x70, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x2c, 0x0a, 0x07, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52,
	0x07, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b,
	0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x70, 0x65, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73,
	0x12, 0x35, 0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x0b,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x65,
	0x63, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x0a, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x1a, 0xd5, 0x01, 0x0a, 0x08, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x06,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73,
	0x1a, 0x5d, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x67,
	0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x1a,
	0xa1, 0x05, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x73, 0x5f, 0x6f, 0x6e, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x73, 0x4f, 0x6e, 0x12,
	0x2e, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e,
	0x56, 0x61, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x76, 0x61, 0x72, 0x73, 0x12,
	0x2c, 0x0a, 0x05, 0x77, 0x61, 0x74, 0x63, 0x68, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x05, 0x77, 0x61, 0x74, 0x63, 0x68, 0x12, 0x37, 0x0a,
	0x09, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x09, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x1a, 0x37, 0x0a, 0x09, 0x56, 0x61, 0x72, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a,
	0x37, 0x0a, 0x05, 0x57, 0x61, 0x74, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x73, 0x1a, 0xd8, 0x01, 0x0a, 0x08, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x75,
	0x74, 0x12, 0x37, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x61, 0x72, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x76, 0x61, 0x72, 0x73, 0x1a, 0x37, 0x0a, 0x09, 0x56, 0x61,
	0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x1a, 0x62, 0x0a, 0x06, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x1a, 0x8f, 0x02, 0x0a, 0x09, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x63,
	0x6c, 0x75, 0x64, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x63,
	0x6c, 0x75, 0x64, 0x65, 0x73, 0x12, 0x33, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70,
	0x65, 0x63, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x52, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x1a, 0x5d, 0x0a, 0x05, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x6e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x2f, 0x70, 0x69, 0x63, 0x61, 0x73, 0x73, 0x6f, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_spec_proto_rawDescOnce sync.Once
	file_pkg_proto_spec_proto_rawDescData = file_pkg_proto_spec_proto_rawDesc
)

func file_pkg_proto_spec_proto_rawDescGZIP() []byte {
	file_pkg_proto_spec_proto_rawDescOnce.Do(func() {
		file_pkg_proto_spec_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_spec_proto_rawDescData)
	})
	return file_pkg_proto_spec_proto_rawDescData
}

var file_pkg_proto_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_proto_spec_proto_goTypes = []interface{}{
	(*Spec)(nil),                 // 0: proto.Spec
	(*Spec_Template)(nil),        // 1: proto.Spec.Template
	(*Spec_Task)(nil),            // 2: proto.Spec.Task
	(*Spec_Plugin)(nil),          // 3: proto.Spec.Plugin
	(*Spec_Generator)(nil),       // 4: proto.Spec.Generator
	(*Spec_Template_Input)(nil),  // 5: proto.Spec.Template.Input
	nil,                          // 6: proto.Spec.Task.VarsEntry
	(*Spec_Task_Watch)(nil),      // 7: proto.Spec.Task.Watch
	(*Spec_Task_Template)(nil),   // 8: proto.Spec.Task.Template
	nil,                          // 9: proto.Spec.Task.Template.VarsEntry
	(*Spec_Generator_Input)(nil), // 10: proto.Spec.Generator.Input
}
var file_pkg_proto_spec_proto_depIdxs = []int32{
	3,  // 0: proto.Spec.plugins:type_name -> proto.Spec.Plugin
	2,  // 1: proto.Spec.tasks:type_name -> proto.Spec.Task
	4,  // 2: proto.Spec.generators:type_name -> proto.Spec.Generator
	5,  // 3: proto.Spec.Template.inputs:type_name -> proto.Spec.Template.Input
	6,  // 4: proto.Spec.Task.vars:type_name -> proto.Spec.Task.VarsEntry
	7,  // 5: proto.Spec.Task.watch:type_name -> proto.Spec.Task.Watch
	8,  // 6: proto.Spec.Task.templates:type_name -> proto.Spec.Task.Template
	10, // 7: proto.Spec.Generator.inputs:type_name -> proto.Spec.Generator.Input
	9,  // 8: proto.Spec.Task.Template.vars:type_name -> proto.Spec.Task.Template.VarsEntry
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_proto_spec_proto_init() }
func file_pkg_proto_spec_proto_init() {
	if File_pkg_proto_spec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_spec_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_spec_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spec_Template); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_spec_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spec_Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_spec_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spec_Plugin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_spec_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spec_Generator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_spec_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spec_Template_Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_spec_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spec_Task_Watch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_spec_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spec_Task_Template); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_spec_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spec_Generator_Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_spec_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_spec_proto_goTypes,
		DependencyIndexes: file_pkg_proto_spec_proto_depIdxs,
		MessageInfos:      file_pkg_proto_spec_proto_msgTypes,
	}.Build()
	File_pkg_proto_spec_proto = out.File
	file_pkg_proto_spec_proto_rawDesc = nil
	file_pkg_proto_spec_proto_goTypes = nil
	file_pkg_proto_spec_proto_depIdxs = nil
}
