// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "4784444fc918d4e2f8d0660b31cb102e"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"d38d4b7263e2299e9ef9bb6394a38bd0": "1f8b08000000000000ff5256a8aed60b28cacf4a4d2ea9ade5aaaed62b492d2ea9ad05040000ffffc4d8f6d318000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("readme", "../templates/readme")
		b.SetResolver("_README.md", packr.Pointer{ForwardBox: gk, ForwardPath: "d38d4b7263e2299e9ef9bb6394a38bd0"})
	}()

	return nil
}()
